import 'package:flutter/material.dart';

/// ÍCONOS "CON VIDA" en todo el app (pedido del director, 29-sep-2026: "a
/// todo el app ponle íconos o imágenes como los de Agregar servicios").
///
/// Un solo lugar decide qué imagen a color va con cada concepto: el mismo
/// ícono de línea de Material se pinta como su emoji (📅 fecha, 📍 dirección,
/// 🏆 campeonatos, 👛 billetera…), igual que ya hacían los servicios extra.
/// Si el ícono no está en el mapa se dibuja el de siempre, así que se puede
/// usar en cualquier lugar donde iba un `Icon` sin romper nada.
///
/// Solo para íconos de CONTENIDO (secciones, menús, datos). Las acciones de la
/// interfaz (cerrar, agregar, flechas, editar, borrar) siguen con su ícono de
/// línea: un emoji ahí confunde más de lo que ayuda.
class IconoVivo extends StatelessWidget {
  const IconoVivo(this.icono, {super.key, this.size, this.color});

  final IconData icono;
  final double? size;

  /// Color del ícono de respaldo (el emoji ya trae el suyo).
  final Color? color;

  /// Emoji asignado a [icono], o null si no tiene.
  static String? emojiDe(IconData icono) {
    if (icono.fontFamily != 'MaterialIcons') return null;
    return _mapa[icono.codePoint];
  }

  @override
  Widget build(BuildContext context) {
    final e = emojiDe(icono);
    final s = size ?? IconTheme.of(context).size ?? 24;
    if (e == null) return Icon(icono, size: s, color: color);
    // El emoji se dibuja un poco más chico que la caja del ícono para que
    // ocupe el mismo espacio visual y no descuadre filas ni Badges.
    return SizedBox(
      width: s,
      height: s,
      child: Center(
        child: Text(e,
            textAlign: TextAlign.center,
            textScaler: TextScaler.noScaling,
            style: TextStyle(fontSize: s * 0.86, height: 1.0)),
      ),
    );
  }
}

final Map<int, String> _mapa = () {
  final m = <int, String>{};
  for (final (ic, e) in <(IconData, String)>[
    (Icons.emoji_events, '🏆'),
    (Icons.emoji_events_outlined, '🏆'),
    (Icons.place, '📍'),
    (Icons.place_outlined, '📍'),
    (Icons.location_on, '📍'),
    (Icons.location_on_rounded, '📍'),
    (Icons.my_location, '📍'),
    (Icons.add_location_alt, '📍'),
    (Icons.add_location_alt_outlined, '📍'),
    (Icons.pin_drop, '📍'),
    (Icons.where_to_vote, '📍'),
    (Icons.edit_location_alt_outlined, '📍'),
    (Icons.share_location, '📍'),
    (Icons.groups, '👥'),
    (Icons.groups_outlined, '👥'),
    (Icons.groups_2_outlined, '👥'),
    (Icons.group_add, '👥'),
    (Icons.account_balance_wallet, '👛'),
    (Icons.account_balance_wallet_outlined, '👛'),
    (Icons.sports_tennis, '🎾'),
    (Icons.sports_tennis_outlined, '🎾'),
    (Icons.campaign, '📣'),
    (Icons.campaign_outlined, '📣'),
    (Icons.verified_user, '🛡️'),
    (Icons.verified_user_outlined, '🛡️'),
    (Icons.shield_outlined, '🛡️'),
    (Icons.admin_panel_settings, '🛡️'),
    (Icons.sports_soccer, '⚽'),
    (Icons.sports_soccer_outlined, '⚽'),
    (Icons.sports, '⚽'),
    (Icons.chat_bubble, '💬'),
    (Icons.chat_bubble_rounded, '💬'),
    (Icons.chat_bubble_outline, '💬'),
    (Icons.chat, '💬'),
    (Icons.chat_outlined, '💬'),
    (Icons.forum_outlined, '💬'),
    (Icons.mode_comment_outlined, '💬'),
    (Icons.schedule, '🕒'),
    (Icons.schedule_outlined, '🕒'),
    (Icons.access_time, '🕒'),
    (Icons.photo_camera, '📷'),
    (Icons.photo_camera_outlined, '📷'),
    (Icons.photo_camera_rounded, '📷'),
    (Icons.camera_alt, '📷'),
    (Icons.camera_alt_outlined, '📷'),
    (Icons.add_a_photo, '📷'),
    (Icons.add_a_photo_outlined, '📷'),
    (Icons.person_add_alt_1, '🙋'),
    (Icons.person_add_alt_1_outlined, '🙋'),
    (Icons.person_add_alt, '🙋'),
    (Icons.person, '👤'),
    (Icons.person_outline, '👤'),
    (Icons.face_outlined, '🙂'),
    (Icons.music_note, '🎵'),
    (Icons.music_note_outlined, '🎵'),
    (Icons.stars, '⭐'),
    (Icons.stars_outlined, '⭐'),
    (Icons.reviews_outlined, '⭐'),
    (Icons.credit_card, '💳'),
    (Icons.credit_card_outlined, '💳'),
    (Icons.add_card, '💳'),
    (Icons.add_card_outlined, '💳'),
    (Icons.confirmation_number, '🎟️'),
    (Icons.confirmation_number_outlined, '🎟️'),
    (Icons.auto_awesome, '✨'),
    (Icons.lock, '🔒'),
    (Icons.lock_outline, '🔒'),
    (Icons.lock_clock, '🔒'),
    (Icons.badge, '🪪'),
    (Icons.badge_outlined, '🪪'),
    (Icons.workspace_premium, '👑'),
    (Icons.storefront, '🏪'),
    (Icons.storefront_outlined, '🏪'),
    (Icons.store_mall_directory_outlined, '🏬'),
    (Icons.receipt_long, '🧾'),
    (Icons.receipt_long_outlined, '🧾'),
    (Icons.notifications_active, '🔔'),
    (Icons.notifications_active_outlined, '🔔'),
    (Icons.notifications_off, '🔕'),
    (Icons.notifications_off_outlined, '🔕'),
    (Icons.payments, '💵'),
    (Icons.payments_outlined, '💵'),
    (Icons.paid_outlined, '💵'),
    (Icons.point_of_sale, '💵'),
    (Icons.point_of_sale_outlined, '💵'),
    (Icons.event, '📅'),
    (Icons.event_outlined, '📅'),
    (Icons.calendar_month, '📅'),
    (Icons.calendar_month_outlined, '📅'),
    (Icons.calendar_today, '📅'),
    (Icons.event_available, '📅'),
    (Icons.today, '📅'),
    (Icons.event_note, '🗓️'),
    (Icons.event_note_outlined, '🗓️'),
    (Icons.date_range, '🗓️'),
    (Icons.event_repeat, '🔁'),
    (Icons.event_busy, '🚫'),
    (Icons.event_busy_outlined, '🚫'),
    (Icons.link, '🔗'),
    (Icons.public, '🌎'),
    (Icons.language, '🌐'),
    (Icons.translate_outlined, '🌐'),
    (Icons.leaderboard, '📊'),
    (Icons.leaderboard_outlined, '📊'),
    (Icons.bar_chart, '📊'),
    (Icons.equalizer, '📊'),
    (Icons.insights, '📈'),
    (Icons.insights_outlined, '📈'),
    (Icons.trending_up, '📈'),
    (Icons.trending_down, '📉'),
    (Icons.school, '🎓'),
    (Icons.school_outlined, '🎓'),
    (Icons.sports_kabaddi, '🤼'),
    (Icons.photo_library_outlined, '🖼️'),
    (Icons.photo_library_rounded, '🖼️'),
    (Icons.image, '🖼️'),
    (Icons.image_outlined, '🖼️'),
    (Icons.add_photo_alternate_outlined, '🖼️'),
    (Icons.savings_outlined, '🐷'),
    (Icons.call_outlined, '📞'),
    (Icons.phone, '📞'),
    (Icons.phone_outlined, '📞'),
    (Icons.phone_android, '📱'),
    (Icons.phone_android_outlined, '📱'),
    (Icons.phone_iphone, '📱'),
    (Icons.person_remove_outlined, '🗑️'),
    (Icons.map, '🗺️'),
    (Icons.map_outlined, '🗺️'),
    (Icons.how_to_reg, '✅'),
    (Icons.how_to_reg_outlined, '✅'),
    (Icons.history, '🕘'),
    (Icons.history_outlined, '🕘'),
    (Icons.favorite, '❤️'),
    (Icons.card_giftcard, '🎁'),
    (Icons.logout, '🚪'),
    (Icons.login, '🔑'),
    (Icons.settings, '⚙️'),
    (Icons.settings_outlined, '⚙️'),
    (Icons.shopping_bag_outlined, '🛍️'),
    (Icons.sports_volleyball, '🏐'),
    (Icons.sports_basketball, '🏀'),
    (Icons.sports_baseball, '⚾'),
    (Icons.sports_handball, '🤾'),
    (Icons.mail_outline, '✉️'),
    (Icons.alternate_email, '✉️'),
    (Icons.fact_check_outlined, '📋'),
    (Icons.assignment_outlined, '📋'),
    (Icons.cleaning_services_outlined, '🧹'),
    (Icons.casino_outlined, '🎲'),
    (Icons.account_balance_outlined, '🏦'),
    (Icons.work_outline, '💼'),
    (Icons.support_agent, '🧑‍💼'),
    (Icons.stadium_outlined, '🏟️'),
    (Icons.sell_outlined, '🏷️'),
    (Icons.local_offer_outlined, '🏷️'),
    (Icons.handshake, '🤝'),
    (Icons.handshake_outlined, '🤝'),
    (Icons.flag_outlined, '🚩'),
    (Icons.family_restroom, '👨‍👩‍👧'),
    (Icons.explore, '🧭'),
    (Icons.explore_outlined, '🧭'),
    (Icons.travel_explore, '🧭'),
    (Icons.directions, '🧭'),
    (Icons.near_me, '🧭'),
    (Icons.directions_walk, '🚶'),
    (Icons.contacts_outlined, '📇'),
    (Icons.checkroom, '👕'),
    (Icons.cake_outlined, '🎂'),
    (Icons.bolt, '⚡'),
    (Icons.speed, '⚡'),
    (Icons.balance_outlined, '⚖️'),
    (Icons.timer_outlined, '⏱️'),
    (Icons.hourglass_top, '⏳'),
    (Icons.hourglass_bottom, '⏳'),
    (Icons.sticky_note_2_outlined, '📝'),
    (Icons.notes, '📝'),
    (Icons.rate_review_outlined, '📝'),
    (Icons.description_outlined, '📄'),
    (Icons.local_fire_department, '🔥'),
    (Icons.local_parking, '🅿️'),
    (Icons.local_drink_outlined, '🥤'),
    (Icons.local_cafe, '☕'),
    (Icons.lightbulb_outline, '💡'),
    (Icons.pool, '🏊'),
    (Icons.shower, '🚿'),
    (Icons.wifi, '📶'),
    (Icons.roofing, '🏠'),
    (Icons.rocket_launch_outlined, '🚀'),
    (Icons.military_tech, '🎖️'),
    (Icons.celebration, '🎉'),
    (Icons.child_care, '🧒'),
    (Icons.local_shipping_outlined, '🚚'),
    (Icons.delivery_dining, '🛵'),
    (Icons.inventory_2_outlined, '📦'),
    (Icons.grass, '🌱'),
    (Icons.apartment, '🏢'),
    (Icons.build_outlined, '🔧'),
    (Icons.build_circle_outlined, '🔧'),
    (Icons.palette_outlined, '🎨'),
    (Icons.brush_outlined, '🖌️'),
    (Icons.dark_mode_outlined, '🌙'),
    (Icons.light_mode_outlined, '☀️'),
    (Icons.volume_up, '🔊'),
    (Icons.visibility_outlined, '👁️'),
    (Icons.video_library_outlined, '🎬'),
    (Icons.movie_creation_outlined, '🎬'),
    (Icons.wb_twilight_outlined, '🌅'),
    (Icons.terrain, '⛰️'),
    (Icons.outdoor_grill, '🍖'),
    (Icons.qr_code_2, '🔳'),
    (Icons.cloud_off, '📴'),
    (Icons.wifi_off, '📴'),
    (Icons.wifi_off_outlined, '📴'),
    (Icons.warning_amber_rounded, '⚠️'),
    (Icons.error_outline, '⚠️'),
    (Icons.person_search, '🔎'),
    (Icons.person_search_outlined, '🔎'),
    (Icons.block, '⛔'),
    (Icons.credit_card_off, '💳'),
    (Icons.credit_card_off_outlined, '💳'),
    (Icons.person_off, '👤'),
    (Icons.person_off_outlined, '👤'),
    (Icons.social_distance, '👥'),
    (Icons.scoreboard_outlined, '🏅'),
    (Icons.hub, '🔗'),
    (Icons.touch_app_outlined, '👆'),
    (Icons.all_inclusive, '♾️'),
  ]) {
    m[ic.codePoint] = e;
  }
  return m;
}();
